let puns = new Map();
puns.set(0, `What's another name for a sapling? Treason.`);
puns.set(1, `What do you call a tree that's not been cleaned? An In-dust-tree.`);
puns.set(2, `What does Yoda say after watching himself in 1080p? HDMI.`);
puns.set(3, `How do you come up with these puns? I'm a pundit.`);
puns.set(4, `What do you call an unidentified tree? A Mystree.`);
puns.set(5, `How do I go about making awesome puns? As with anything you get started with the Pundamentals.`);
puns.set(6, `You can count me to make puns, I'm very depundadable.`);
puns.set(7, `What do you call a Jalapeno whose seeds have been removed? A Hollow-peno`);
puns.set(9, `If a naughty kid makes a sausage, is it called a Bratwurst?`);
puns.set(10, `How do you determine a pig's colour? You check it's Pigment`);
export default puns;
